### ISSUE TITLE
I can't run the demo

### ISSUE THREAD

**Issue by laixintao** [rittamdebnath/BookYourSeats#11]
I fellow as you said, git clone the repo, run nom install, then gulp, but can not get locaohost:8080.

Gulp output as fellows:
![image](https://cloud.githubusercontent.com/assets/9675939/21667135/68bcd8ec-d331-11e6-96b8-0661dc902768.png)

Chrome said this site can't be reached.

**Comment by rittamdebnath** [comment]
Once can you download the previous push.

**Comment by laixintao** [comment]
Since the latest commit were "update package.json", I don't know which commit can work, could you please give me a commit id that can run? if you have time. Thanks!

**Comment by rittamdebnath** [comment]
It's working in my distro. Once try changing the port from 8080 to 8000 in the gulpfile.js

```javascript
gulp.task('connect', function() {
    connect.server({
        root: '',
	      port: 8000,
        livereload: true
    });
});

```

**Comment by laixintao** [comment]
![image](https://cloud.githubusercontent.com/assets/9675939/21704245/eace5c36-d3f2-11e6-8655-d63e0c2ecec0.png)

Thanks, I edited the gulp file, bug seems that still has error. Thanks for your replay, I guess I am going to write a seat picker by myself. :+1:
