### ISSUE TITLE
Checked seats are not getting booked after finish

### ISSUE THREAD

**Issue by rittamdebnath** [rittamdebnath/BookYourSeats#2]
![ticketdekho_com___ticket_to_movies_and_more___](https://cloud.githubusercontent.com/assets/7520259/16066037/980b68de-32cd-11e6-9e43-62f63019360b.png)

Blocked Seats should be visible when the user changes the seat quantiy and also the seat quality. the user should not be able to uncheck or change the blocked seats once booked. 

![booked seats](https://cloud.githubusercontent.com/assets/7520259/16066239/423d3eb2-32cf-11e6-849a-e937a1950208.gif)
## Description

when the user clicks on the finish button after the selection the `storeSeat function in the quantityModuleController` should execute and in that function the logic should check each and every seat and check whether it is checked or not if it is checked then make it uncheck and the blocked should be true.

thus whenever the user selects new pair of options then the user should see the blocked seats as grey in color and should be disabled from clicking as shown in the GIF.

**Comment by AWolf81** [comment]
OK, I've fixed this. There was a naming issue in `ng-class` expression and the `storeSeat` was using the wrong collection (old reference to rows).

I'll commit this soon.
