### ISSUE TITLE
Seat Quality is not visible

### ISSUE THREAD

**Issue by rittamdebnath** [rittamdebnath/BookYourSeats#3]
![seat quality check](https://cloud.githubusercontent.com/assets/7520259/16066276/801272de-32cf-11e6-855a-c7608c5512b3.png)

**Comment by AWolf81** [comment]
I've fixed this. The expression was not matching the controller definition. I'll commit this soon. Now I'm doing a default value on start of app to `Standard` but also start with-out selection would be possible.

But I think it's better to show seats at start.
