### ISSUE TITLE
Checking available seats between booked is checking booked seats

### ISSUE THREAD

**Issue by AWolf81** [rittamdebnath/BookYourSeats#4]
If you click in between two booked seats and you'd like to select more then the available space it will incorrectly check booked seats. The followin screenshot is before clicking seat no. 6:
![seat select issue](http://i.imgur.com/eI0DmA9.png)

And afterward it will look like this and no seat available to select:
![after click](http://i.imgur.com/EByIFPv.png)

I think that's easy to add to the border calculation. I'll add this asap.

**Comment by rittamdebnath** [comment]
Okay can you please push these edits asap 😄

**Comment by AWolf81** [comment]
OK, this is fixed in my devel branch. 
Now I'm checking two borders. Booked is one border and the other is the end of the row.
