### ISSUE TITLE
Users should be able to select seats in any one of the seat Quality but not both.

### ISSUE THREAD

**Issue by rittamdebnath** [rittamdebnath/BookYourSeats#6]
lets say that user have selected 3 seat quantity and chose to select from premium then the user should not be able to select one seat in premium then jump to 'standard' and select the remaining two in standard seat quality. 

**Important**
- The user should select all the 3 from one seat quality only.
- i.e. SeatsLeft should reset to the selectedQuantity for every change in the seatQuality and uncheck all the previously checked seats.

**Comment by jimut** [comment]
I worked on the ver1.1 branch. 
The above issue can be solved if the following two line are added at the end of showQuality function in service.js.

``` javascript
this.availCount.val = this.availCount.id;  
removeAllCheck();
```
