### ISSUE TITLE
Json Stringify

### ISSUE THREAD

**Issue by rittamdebnath** [rittamdebnath/BookYourSeats#7]
![screen shot 2016-06-16 at 8 23 00 am](https://cloud.githubusercontent.com/assets/7520259/16104073/997e040a-339b-11e6-9b73-63b801bd7d65.png)

Instead of JSON Stringify, can you make it display only the seat value and the seat letter like 

You have selected 3 seats , 3B,3C,3D.

**Comment by rittamdebnath** [comment]
#7 Similarly 1G,1H,2H

**Comment by rittamdebnath** [comment]
from now on make all the changes in the ver1.1 the **controller.js**,**service.js** and **module.js** are inside `scripts/quantity/` folder.

**Comment by jimut** [comment]
``` javascript
currentSelectionSession.checkedSeats[rang][seatIndex] = seat;
```

This line was overwriting the seats of the same columns. Solved this one. 
Creating a pull request in a moment.
